UHM-4998, migrate PCR tests
PIH/hivmigration pull request #88
Opened 2020-11-13 20:48 UTC by cioan

Hi @mogoodrich , here is the PR for migrating the PCR tests. Thanks!

2020-11-13 22:06 UTC, mogoodrich requested changes
Generally LGTM @cioan , though I requested a few changes, thanks!

2020-11-13 22:06 UTC, mogoodrich commented on etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
> +                    r.source_encounter_date as dateCreated,
I would use result_entry_date here

2020-11-13 22:06 UTC, mogoodrich commented on etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
> +                    r.source_encounter_date as dateCreated,
I would use result_entry_date here

2020-11-13 22:06 UTC, mogoodrich commented on etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
> +                        else to_char(RESULT_ENTRY_DATE, 'yyyy-mm-dd')
I think we can just use date_result_received here, and just keep null if there's no date result received (and then don't create an "date of results" obs below for these entries)...

2020-11-13 22:06 UTC, mogoodrich commented on etl/src/main/java/org/pih/hivmigration/etl/sql/PcrTestsMigrator.groovy
> +            SET @date_of_test_results = (concept_from_mapping('PIH', 'DATE OF LABORATORY TEST'));
Per my comment above, fine to just not create this obs for any results that don't have a "date of result received"

2020-11-13 23:22 UTC, cioan commented
Thanks @mogoodrich ! I have addressed all your requests. Thanks!

2020-11-16 16:33 UTC, mogoodrich approved these changes
LGTM, thanks @cioan !

2020-11-16 16:35 UTC, merged

2020-11-16 16:35 UTC, cioan commented
Thanks @mogoodrich !